foreground            #e5e2de
background            #131411
selection_foreground  #2c331b
selection_background  #c6d0ad
url_color             #e2c3d8
cursor                #c6d0ad
cursor_text_color     #2c331b

color0   #131411
color1   #ffb4ab
color2   #c6d0ad
color3   #e2c3d8
color4   #c6d0ad
color5   #e2c3d8
color6   #c5a8bc
color7   #e5e2de

color8   #909287
color9   #ffb4ab
color10  #c6d0ad
color11  #e2c3d8
color12  #c6d0ad
color13  #e2c3d8
color14  #c5a8bc
color15  #e5e2de

tab_bar_background              #131411
tab_bar_margin_color            #131411
active_tab_foreground           #2c331b
active_tab_background           #c6d0ad
inactive_tab_foreground         #c7c7bc
inactive_tab_background         #131411
