#!/bin/bash

case "$1" in
    w)
        while read file; do
            wal -i "$file"
            hyprctl hyprpaper preload "$file"
            hyprctl hyprpaper wallpaper ,"$file"
            hyprctl hyprpaper unload unused
            $HOME/.config/hypr/scripts/colors.sh
            echo "$file" > "$HOME/.cache/current-wallpaper"
        done
        ;;
esac
