#!/bin/bash

case "$1" in
    w)
        while read file; do
            wal -i "$file"
            hyprctl hyprpaper preload "$file"
            hyprctl hyprpaper wallpaper HDMI-A-1 ,"$file"
            hyprctl hyprpaper wallpaper DP-1 ,"$file"
            hyprctl hyprpaper unload unused
            $HOME/.config/hypr/scripts/colors.sh
            echo "$file" > ~/.cache/current-wallpaper
        done
        ;;
esac
