
wallpaper { 
    monitor = DP-1 
    path = /home/answet/Pictures/Wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/answet/Pictures/Wallpapers/wallpaper.jpg
    fit_mode = cover
}
 
#wallpaper {
#    monitor = HDMI-A-1
#    path = /home/answet/Pictures/Wallpaper/fondo.png
#    fit_mode = cover
#}
splash = false
