#!/usr/bin/env bash


if [[ $# -ne 1 ]]; then
    echo "Uso: $(basename "$0") <archivo_de_colores>"
    exit 1
fi

FILE="$1"

[[ -f "$FILE" ]] || {
    echo "No existe: $FILE"
    exit 1
}

i=0

while IFS= read -r color; do
    [[ -z "$color" ]] && continue

    if [[ "$color" =~ ^#([[:xdigit:]]{6})$ ]]; then
      r=$((16#${color:1:2}))
      g=$((16#${color:3:2}))
      b=$((16#${color:5:2}))

    elif [[ "$color" =~ ^([0-9]{1,3}),([0-9]{1,3}),([0-9]{1,3})$ ]]; then
      r=${BASH_REMATCH[1]}
      g=${BASH_REMATCH[2]}
      b=${BASH_REMATCH[3]}
    else
      echo "Formato inválido: $color"
      continue
    fi

    printf "%2d  \e[48;2;%d;%d;%dm        \e[0m  %s\n" \
      "$i" "$r" "$g" "$b" "$color"

    ((i++))
done < "$FILE"
